# Generated by Django 4.1.2 on 2023-05-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cart_image'),
        ),
    ]
