# Generated by Django 4.1.2 on 2023-05-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_amt',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
