# Generated by Django 4.1.2 on 2023-05-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_orderitems_product_alter_orderitems_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='orders_id',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='qty',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='total',
            field=models.PositiveIntegerField(),
        ),
    ]
