# Generated by Django 4.1.2 on 2023-05-31 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_orderitems_orders_id_remove_orderitems_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='product',
        ),
    ]
